name: Apptainer Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    container:
        image: ghcr.io/apptainer/apptainer:1.4.1
        options: --privileged

    name: Build Container
    steps:

      - name: Install Git
        run: |
          apt-get update
          apt-get install -y git
          git --version

      - name: Check out code for the container builds
        uses: actions/checkout@v4
        with:
          submodules: recursive  # This initializes and updates submodules recursively

      - name: Build Apptainer Image
        run: |
           apptainer build saga.sif singularity/saga.def

      - name: Set image tags dynamically
        id: vars
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            # On push to main → publish production tag
            echo "tag=latest" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # On PR to main → publish preview image with PR number
            echo "tag=pr-${{ github.event.number }}" >> $GITHUB_OUTPUT
          fi

      - name: Push SIF to GHCR using ORAS
        # Use default registry user ${{ github.repository_owner }} , or set a secret ${{ secrets.GHCR_USERNAME }}
        run: |
           echo ${{ secrets.GITHUB_TOKEN }} | apptainer registry login -u ${{ github.repository_owner }} --password-stdin oras://ghcr.io
           apptainer push saga.sif oras://ghcr.io/${{ github.repository }}-apptainer:${{ steps.vars.outputs.tag }}
